// AT Protocol glossary data.
// Each entry: { term, abbr?, aka?, cat, def, ref, refLabel? }
// `def` may contain simple inline markup: **bold**, `code`, and [[Other Term]]
// cross-links (matched case-insensitively against another entry's `term`).

const CATEGORIES = [
  {
    id: 'basics',
    name: 'Big picture',
    blurb: 'The core ideas: what the protocol is and the goals that shape it.',
  },
  {
    id: 'identity',
    name: 'Identity',
    blurb: 'How accounts are named and proven — DIDs, handles, and keys.',
  },
  {
    id: 'data',
    name: 'Data & repositories',
    blurb: 'How a user’s data is structured, stored, and cryptographically signed.',
  },
  {
    id: 'identifiers',
    name: 'Identifiers & formats',
    blurb: 'The string and binary formats used to name and encode everything.',
  },
  {
    id: 'lexicon',
    name: 'Lexicon & APIs',
    blurb: 'The schema language and the HTTP API layer built on top of it.',
  },
  {
    id: 'network',
    name: 'Network infrastructure',
    blurb: 'The independent services that make the open network work.',
  },
  {
    id: 'auth',
    name: 'Auth & security',
    blurb: 'How clients and services authenticate and authorise requests.',
  },
  {
    id: 'moderation',
    name: 'Moderation',
    blurb: 'Labels, labelers, and the stackable moderation model.',
  },
  {
    id: 'bluesky',
    name: 'Bluesky app terms',
    blurb: 'Terms specific to Bluesky, the first big app built on atproto.',
  },
  {
    id: 'ecosystem',
    name: 'Ecosystem',
    blurb: 'Organisations, tools, and community shorthand.',
  },
];

const TERMS = [
  // ---------------------------------------------------------------- basics
  {
    term: 'AT Protocol',
    abbr: 'atproto',
    aka: ['Authenticated Transfer Protocol'],
    cat: 'basics',
    def: 'The **A**uthenticated **T**ransfer Protocol — an open, decentralised networking protocol for social apps. User data lives in signed [[Repository|repositories]] that can be independently verified, so applications can be built on shared, portable data instead of a single company’s silo.',
    ref: 'https://atproto.com/',
    refLabel: 'atproto.com',
  },
  {
    term: 'Atmosphere',
    aka: ['atmo'],
    cat: 'basics',
    def: 'The whole ecosystem of accounts, services, and applications running on the AT Protocol — not just Bluesky. Analogous to “the web” being the ecosystem built on HTTP.',
    ref: 'https://atproto.com/guides/glossary',
    refLabel: 'Glossary',
  },
  {
    term: 'Decentralisation',
    aka: ['decentralization'],
    cat: 'basics',
    def: 'No single company owns the network. Anyone can run the core services ([[PDS]], [[Relay]], [[AppView]]), host their own data, and build competing apps that all interoperate.',
    ref: 'https://atproto.com/guides/faq',
    refLabel: 'FAQ',
  },
  {
    term: 'Federation',
    cat: 'basics',
    def: 'Independent servers cooperating to form one network. In atproto, many [[PDS]] hosts store users’ data and a [[Relay]] aggregates it, so an account on one server can interact with accounts anywhere.',
    ref: 'https://atproto.com/guides/self-hosting',
    refLabel: 'Self-hosting guide',
  },
  {
    term: 'Account portability',
    aka: ['portability'],
    cat: 'basics',
    def: 'A user can move their account and all its data from one [[PDS]] to another without losing their identity or followers, because their [[DID]] and signed [[Repository]] travel with them. A key design goal of the protocol.',
    ref: 'https://atproto.com/guides/account-migration',
    refLabel: 'Account migration',
  },
  {
    term: 'Credible exit',
    cat: 'basics',
    def: 'The principle that leaving a service must be genuinely practical, not just theoretically possible — achieved through [[Account portability]], open data, and open protocols so users are never locked in.',
    ref: 'https://atproto.com/guides/faq',
    refLabel: 'FAQ',
  },
  {
    term: 'Algorithmic choice',
    cat: 'basics',
    def: 'Users pick which [[Feed generator|feeds]] and [[Labeler|moderation services]] they subscribe to, rather than being subject to one company’s single algorithm. Ranking and moderation become an open marketplace.',
    ref: 'https://atproto.com/guides/faq',
    refLabel: 'FAQ',
  },
  {
    term: 'Speech vs. reach',
    cat: 'basics',
    def: 'A design philosophy separating the right to post (speech, handled at the infrastructure layer) from amplification and curation (reach, handled by composable [[Labeler|labelers]] and [[Feed generator|feeds]]).',
    ref: 'https://bsky.social/about/blog/4-13-2023-moderation',
    refLabel: 'Moderation blog post',
  },

  // -------------------------------------------------------------- identity
  {
    term: 'DID',
    abbr: 'Decentralised Identifier',
    cat: 'identity',
    def: 'A permanent, globally-unique, machine-readable identifier for an account, e.g. `did:plc:z72i7hd…`. It never changes, even if the [[Handle]] or [[PDS]] does, and resolves to a [[DID document]]. atproto supports two methods: [[did:plc]] and [[did:web]].',
    ref: 'https://atproto.com/specs/did',
    refLabel: 'DID spec',
  },
  {
    term: 'DID document',
    aka: ['DID doc'],
    cat: 'identity',
    def: 'The JSON metadata a [[DID]] resolves to. It lists the account’s current [[Handle]], its [[Signing key]] (verification method), and its [[PDS]] service endpoint. This is what lets anyone verify records and find where data lives.',
    ref: 'https://atproto.com/specs/did',
    refLabel: 'DID spec',
  },
  {
    term: 'did:plc',
    aka: ['PLC'],
    cat: 'identity',
    def: 'The default [[DID]] method in atproto. “PLC” stands for **P**ublic **L**edger of **C**redentials — a self-authenticating identifier whose history is stored in the [[PLC directory]]. Cryptographically controlled by [[Rotation key|rotation keys]], so it survives server migration.',
    ref: 'https://web.plc.directory/spec/v0.1/did-plc',
    refLabel: 'did:plc spec',
  },
  {
    term: 'did:web',
    cat: 'identity',
    def: 'A [[DID]] method that anchors identity to a domain name you control, resolving via `https://example.com/.well-known/did.json`. Fully self-hosted, but not portable the way [[did:plc]] is — lose the domain, lose the identity.',
    ref: 'https://atproto.com/specs/did',
    refLabel: 'DID spec',
  },
  {
    term: 'PLC directory',
    aka: ['plc.directory'],
    cat: 'identity',
    def: 'The service that stores the operation history for [[did:plc]] identifiers, mapping each DID to its current keys, [[Handle]], and [[PDS]]. Currently run by Bluesky as a transparent, auditable log; designed to be replaceable.',
    ref: 'https://web.plc.directory/',
    refLabel: 'plc.directory',
  },
  {
    term: 'Handle',
    cat: 'identity',
    def: 'The human-readable username for an account, which is always a domain name — e.g. `@alice.bsky.social` or `@nytimes.com`. Handles can change and are looked up to find the account’s permanent [[DID]] (see [[Handle resolution]]).',
    ref: 'https://atproto.com/specs/handle',
    refLabel: 'Handle spec',
  },
  {
    term: 'Handle resolution',
    cat: 'identity',
    def: 'The process of turning a [[Handle]] into a [[DID]]. Done either via a DNS `TXT` record at `_atproto.<handle>` or an HTTPS request to `/.well-known/atproto-did`. Because handles are domains, controlling the domain proves the handle.',
    ref: 'https://atproto.com/specs/handle',
    refLabel: 'Handle spec',
  },
  {
    term: 'Signing key',
    cat: 'identity',
    def: 'The private key used to sign a [[Repository]]’s [[Commit|commits]]. Its public half lives in the [[DID document]], so anyone can verify that records genuinely came from that account. Usually held by the [[PDS]].',
    ref: 'https://atproto.com/specs/cryptography',
    refLabel: 'Cryptography spec',
  },
  {
    term: 'Rotation key',
    cat: 'identity',
    def: 'A key that authorises changes to a [[did:plc]] identity — updating the [[Signing key]], [[Handle]], or [[PDS]] endpoint. Holding a rotation key is what makes [[Account portability]] and [[Credible exit]] possible.',
    ref: 'https://web.plc.directory/spec/v0.1/did-plc',
    refLabel: 'did:plc spec',
  },
  {
    term: 'Verification method',
    cat: 'identity',
    def: 'The entry in a [[DID document]] that publishes a public key. Clients use it to check the signature on a [[Commit]], confirming a [[Record]] is authentic and untampered.',
    ref: 'https://atproto.com/specs/did',
    refLabel: 'DID spec',
  },

  // ------------------------------------------------------------------ data
  {
    term: 'Repository',
    abbr: 'repo',
    cat: 'data',
    def: 'The signed data structure holding all of one account’s public data. It’s a collection of [[Collection|collections]] of [[Record|records]], organised in a [[Merkle Search Tree]] and signed with the account’s [[Signing key]]. Identified by its [[DID]].',
    ref: 'https://atproto.com/specs/repository',
    refLabel: 'Repository spec',
  },
  {
    term: 'Record',
    cat: 'data',
    def: 'A single JSON document in a [[Repository]] — one post, like, follow, or profile. Its shape is defined by a [[Lexicon]] and named by its `$type`. Addressed by an [[AT-URI]] and content-addressed by a [[CID]].',
    ref: 'https://atproto.com/specs/repository',
    refLabel: 'Repository spec',
  },
  {
    term: 'Collection',
    cat: 'data',
    def: 'A named bucket of [[Record|records]] of the same type inside a [[Repository]], keyed by an [[NSID]] such as `app.bsky.feed.post`. All of an account’s posts live in one collection, all follows in another, etc.',
    ref: 'https://atproto.com/specs/repository',
    refLabel: 'Repository spec',
  },
  {
    term: 'Blob',
    cat: 'data',
    def: 'Unstructured binary data — images, video, other media — referenced from a [[Record]] by its [[CID]] rather than stored inline. Blobs are uploaded to and served by the [[PDS]].',
    ref: 'https://atproto.com/specs/blob',
    refLabel: 'Blob spec',
  },
  {
    term: 'Commit',
    aka: ['signed commit'],
    cat: 'data',
    def: 'The signed root of a [[Repository]] at a point in time. Each change produces a new commit, signed with the [[Signing key]] and carrying a [[rev]]. Verifying the commit signature verifies the whole repo state.',
    ref: 'https://atproto.com/specs/repository',
    refLabel: 'Repository spec',
  },
  {
    term: 'Merkle Search Tree',
    abbr: 'MST',
    cat: 'data',
    def: 'The tree structure that organises a [[Repository]]’s records. It maps record keys to [[CID|CIDs]] and produces a single root hash, enabling efficient, verifiable diffs and sync between servers.',
    ref: 'https://atproto.com/specs/repository',
    refLabel: 'Repository spec',
  },
  {
    term: 'rev',
    aka: ['revision'],
    cat: 'data',
    def: 'A monotonically increasing revision marker (a [[TID]]) on each [[Commit]]. It lets services tell which version of a [[Repository]] is newer and detect whether they are behind.',
    ref: 'https://atproto.com/specs/repository',
    refLabel: 'Repository spec',
  },
  {
    term: 'Tombstone',
    cat: 'data',
    def: 'A marker indicating an account or record has been deleted, propagated through [[Sync|sync events]] so downstream services ([[Relay]], [[AppView]]) can remove the data too.',
    ref: 'https://atproto.com/specs/sync',
    refLabel: 'Sync spec',
  },

  // ----------------------------------------------------------- identifiers
  {
    term: 'AT-URI',
    aka: ['at:// URI', 'AT URI'],
    cat: 'identifiers',
    def: 'The URI scheme that addresses any [[Record]] in the network, e.g. `at://did:plc:…/app.bsky.feed.post/3jz…`. Structure is `at://<repo>/<collection>/<rkey>` — the [[DID]] (or [[Handle]]), the [[NSID]] collection, and the [[Record Key]].',
    ref: 'https://atproto.com/specs/at-uri-scheme',
    refLabel: 'AT-URI spec',
  },
  {
    term: 'NSID',
    abbr: 'Namespaced Identifier',
    cat: 'identifiers',
    def: 'A reverse-DNS name identifying a [[Lexicon]] schema (and therefore a [[Collection]] or API method), e.g. `app.bsky.feed.post`. The domain segment establishes who owns and defines that schema.',
    ref: 'https://atproto.com/specs/nsid',
    refLabel: 'NSID spec',
  },
  {
    term: 'TID',
    abbr: 'Timestamp Identifier',
    cat: 'identifiers',
    def: 'A compact, sortable identifier derived from a timestamp (plus a random component to avoid collisions). Commonly used as a [[Record Key]] and as the [[rev]] on commits, giving records a natural chronological order.',
    ref: 'https://atproto.com/specs/tid',
    refLabel: 'TID spec',
  },
  {
    term: 'Record Key',
    abbr: 'rkey',
    cat: 'identifiers',
    def: 'The identifier for a single [[Record]] within its [[Collection]]. Usually a [[TID]] (like `3jzfcijpj2z2a`), but can be a fixed literal such as `self` for singleton records like a profile.',
    ref: 'https://atproto.com/specs/record-key',
    refLabel: 'Record Key spec',
  },
  {
    term: 'CID',
    abbr: 'Content Identifier',
    cat: 'identifiers',
    def: 'A cryptographic hash that content-addresses a [[Record]] or [[Blob]] — the same bytes always produce the same CID. Used to pin exact versions and verify integrity. A multiformats standard shared with IPFS.',
    ref: 'https://github.com/multiformats/cid',
    refLabel: 'CID spec',
  },
  {
    term: 'DAG-CBOR',
    cat: 'identifiers',
    def: 'The binary serialisation format used for [[Record|records]] and [[Commit|commits]] when signing and hashing. It has a strict canonical form so the same data always yields the same bytes — essential for reproducible [[CID|CIDs]] and signatures.',
    ref: 'https://ipld.io/specs/codecs/dag-cbor/spec/',
    refLabel: 'DAG-CBOR spec',
  },
  {
    term: 'CAR file',
    abbr: 'Content Addressable aRchive',
    cat: 'identifiers',
    def: 'A file format bundling many content-addressed blocks into one archive. Used to export or sync a whole [[Repository]] in a single download — e.g. when migrating an account.',
    ref: 'https://ipld.io/specs/transport/car/carv1/',
    refLabel: 'CAR spec',
  },

  // -------------------------------------------------------------- lexicon
  {
    term: 'Lexicon',
    cat: 'lexicon',
    def: 'atproto’s schema language, defined in JSON. It describes the shape of [[Record|records]] and the [[XRPC]] API methods, much like JSON-Schema plus OpenAPI. Every schema is named by an [[NSID]], so schemas are globally addressable and extensible.',
    ref: 'https://atproto.com/specs/lexicon',
    refLabel: 'Lexicon spec',
  },
  {
    term: 'XRPC',
    aka: ['Cross-organisational RPC'],
    cat: 'lexicon',
    def: 'The HTTP API convention for atproto. Methods are named by [[NSID]] and called at `/xrpc/<nsid>` — `GET` for a [[Query]], `POST` for a [[Procedure]]. Request and response shapes come from the method’s [[Lexicon]].',
    ref: 'https://atproto.com/specs/xrpc',
    refLabel: 'XRPC spec',
  },
  {
    term: 'Query',
    cat: 'lexicon',
    def: 'A read-only [[XRPC]] method, called with `GET`, e.g. `app.bsky.feed.getTimeline`. Defined in a [[Lexicon]] with typed parameters and output.',
    ref: 'https://atproto.com/specs/lexicon',
    refLabel: 'Lexicon spec',
  },
  {
    term: 'Procedure',
    cat: 'lexicon',
    def: 'A write / action [[XRPC]] method, called with `POST`, e.g. `com.atproto.repo.createRecord`. The counterpart to a [[Query]].',
    ref: 'https://atproto.com/specs/lexicon',
    refLabel: 'Lexicon spec',
  },
  {
    term: 'Subscription',
    cat: 'lexicon',
    def: 'A [[Lexicon]] method type for a streaming connection over WebSocket, used for event streams like the [[Firehose]] (`com.atproto.sync.subscribeRepos`).',
    ref: 'https://atproto.com/specs/event-stream',
    refLabel: 'Event stream spec',
  },
  {
    term: '$type',
    cat: 'lexicon',
    def: 'The field on a [[Record]] (or nested object) naming the [[Lexicon]] schema it conforms to, given as an [[NSID]]. It tells software how to interpret the JSON.',
    ref: 'https://atproto.com/specs/data-model',
    refLabel: 'Data model spec',
  },
  {
    term: 'com.atproto',
    cat: 'lexicon',
    def: 'The [[NSID]] namespace for core protocol [[Lexicon|lexicons]] — the app-neutral methods every service shares, like `com.atproto.repo.createRecord` and `com.atproto.sync.subscribeRepos`.',
    ref: 'https://github.com/bluesky-social/atproto/tree/main/lexicons',
    refLabel: 'Core lexicons',
  },
  {
    term: 'app.bsky',
    cat: 'lexicon',
    def: 'The [[NSID]] namespace for Bluesky’s application [[Lexicon|lexicons]] — posts, likes, follows, feeds, profiles. Other apps define their own namespaces under domains they control.',
    ref: 'https://github.com/bluesky-social/atproto/tree/main/lexicons/app/bsky',
    refLabel: 'Bluesky lexicons',
  },

  // -------------------------------------------------------------- network
  {
    term: 'PDS',
    abbr: 'Personal Data Server',
    cat: 'network',
    def: 'The server that hosts an account: it stores the user’s [[Repository]] and [[Blob|blobs]], handles login, signs [[Commit|commits]], and emits events when data changes. Anyone can run one; users can migrate between them.',
    ref: 'https://atproto.com/guides/self-hosting',
    refLabel: 'Self-hosting guide',
  },
  {
    term: 'Relay',
    aka: ['BGS', 'Big Graph Service'],
    cat: 'network',
    def: 'A service that crawls many [[PDS]] hosts, aggregates their repositories, and republishes all the changes as a single [[Firehose]]. It does the heavy lifting of network-wide sync so [[AppView|AppViews]] don’t each have to poll every PDS. (Formerly “BGS”.)',
    ref: 'https://atproto.com/guides/glossary',
    refLabel: 'Glossary',
  },
  {
    term: 'AppView',
    cat: 'network',
    def: 'A service that consumes the [[Firehose]], indexes the network’s data, and serves it back as an application — timelines, threads, profiles, counts. This is the “backend” of an app like Bluesky; different AppViews present different products from the same data.',
    ref: 'https://atproto.com/guides/glossary',
    refLabel: 'Glossary',
  },
  {
    term: 'Firehose',
    cat: 'network',
    def: 'The continuous, ordered WebSocket stream of every [[Repository]] change across the network, emitted by a [[Relay]] via `com.atproto.sync.subscribeRepos`. It carries signed [[Commit|commits]] so consumers can verify them. See also [[Jetstream]].',
    ref: 'https://docs.bsky.app/docs/advanced-guides/firehose',
    refLabel: 'Firehose docs',
  },
  {
    term: 'Jetstream',
    cat: 'network',
    def: 'A lighter-weight alternative to the [[Firehose]] that streams the same events as plain JSON (not signed [[DAG-CBOR]]). Easier to consume for bots and simple apps, at the cost of not being independently verifiable.',
    ref: 'https://github.com/bluesky-social/jetstream',
    refLabel: 'Jetstream repo',
  },
  {
    term: 'Feed generator',
    aka: ['custom feed', 'feedgen'],
    cat: 'network',
    def: 'A third-party service that produces a custom, algorithmic feed of posts. It consumes the [[Firehose]], applies whatever logic it likes, and returns a list of post [[AT-URI|URIs]] when the [[AppView]] asks. The mechanism behind [[Algorithmic choice]].',
    ref: 'https://docs.bsky.app/docs/starter/custom-feeds',
    refLabel: 'Custom feeds guide',
  },
  {
    term: 'Entryway',
    cat: 'network',
    def: 'An OAuth/account-management service that fronts one or more [[PDS]] instances, handling sign-up, login, and [[DID]] creation. Bluesky’s hosted service uses an entryway in front of many PDS hosts.',
    ref: 'https://github.com/bluesky-social/atproto/tree/main/packages/pds',
    refLabel: 'PDS package',
  },
  {
    term: 'Sync',
    aka: ['repo sync', 'subscribeRepos'],
    cat: 'network',
    def: 'The mechanism by which services keep copies of [[Repository|repositories]] up to date — streaming signed [[Commit|commits]] over the [[Firehose]] and backfilling history via [[CAR file|CAR]] exports. Defined by the sync spec.',
    ref: 'https://atproto.com/specs/sync',
    refLabel: 'Sync spec',
  },

  // ------------------------------------------------------------------ auth
  {
    term: 'OAuth',
    cat: 'auth',
    def: 'The standard way third-party apps get scoped, revocable access to an account without handling the password. atproto uses OAuth 2.0 with [[DPoP]] and dynamic client registration. It is replacing [[App Password|app passwords]] as the recommended auth method.',
    ref: 'https://atproto.com/specs/oauth',
    refLabel: 'OAuth spec',
  },
  {
    term: 'DPoP',
    abbr: 'Demonstrating Proof of Possession',
    cat: 'auth',
    def: 'An OAuth mechanism that binds access tokens to a client-held key, so a stolen token can’t be replayed by someone else. Required by atproto’s [[OAuth]] implementation.',
    ref: 'https://atproto.com/specs/oauth',
    refLabel: 'OAuth spec',
  },
  {
    term: 'App Password',
    aka: ['app password'],
    cat: 'auth',
    def: 'A secondary, revocable password a user generates for a third-party client, so they never share their main password. Simpler than [[OAuth]] but coarse-grained; being superseded by OAuth for most apps.',
    ref: 'https://docs.bsky.app/docs/starter/clients',
    refLabel: 'Clients guide',
  },
  {
    term: 'Service auth',
    aka: ['inter-service auth', 'service JWT'],
    cat: 'auth',
    def: 'Short-lived signed JWTs a service uses to prove its identity when calling another service on a user’s behalf — e.g. a [[PDS]] authenticating to an [[AppView]] or [[Feed generator]]. Signed with the account’s key and verifiable via its [[DID document]].',
    ref: 'https://atproto.com/specs/xrpc#inter-service-authentication-temporary-specification',
    refLabel: 'XRPC spec',
  },
  {
    term: 'Session',
    aka: ['access token', 'refresh token'],
    cat: 'auth',
    def: 'The tokens issued after login. A short-lived access token authorises [[XRPC]] calls to the [[PDS]]; a longer-lived refresh token renews it. Created via `com.atproto.server.createSession`.',
    ref: 'https://docs.bsky.app/docs/advanced-guides/api-directory',
    refLabel: 'API docs',
  },

  // ------------------------------------------------------------ moderation
  {
    term: 'Label',
    cat: 'moderation',
    def: 'A small piece of moderation metadata attached to an account or [[Record]] — e.g. `!hide`, `spam`, `porn`. Labels are emitted by [[Labeler|labelers]] and applied by clients according to the user’s settings.',
    ref: 'https://atproto.com/specs/label',
    refLabel: 'Label spec',
  },
  {
    term: 'Labeler',
    aka: ['label service', 'labelling service'],
    cat: 'moderation',
    def: 'A service that publishes [[Label|labels]] over the network. Users subscribe to the labelers they trust, and clients stack their labels — composable, opt-in moderation instead of one central authority.',
    ref: 'https://docs.bsky.app/docs/advanced-guides/moderation',
    refLabel: 'Moderation docs',
  },
  {
    term: 'Ozone',
    cat: 'moderation',
    def: 'Bluesky’s open-source moderation tooling — the console operators use to review reports and issue [[Label|labels]] and takedowns. Anyone running a [[Labeler]] can self-host it.',
    ref: 'https://github.com/bluesky-social/ozone',
    refLabel: 'Ozone repo',
  },
  {
    term: 'Takedown',
    cat: 'moderation',
    def: 'Removal of content or an account by a service that hosts or indexes it (a [[PDS]] or [[AppView]]). Distinct from a [[Label]], which annotates rather than removes. Infrastructure-level takedowns affect availability; labels affect [[Speech vs. reach|reach]].',
    ref: 'https://docs.bsky.app/docs/advanced-guides/moderation',
    refLabel: 'Moderation docs',
  },
  {
    term: 'Block',
    cat: 'moderation',
    def: 'A public [[Record]] (`app.bsky.graph.block`) declaring that an account should not interact with the user. Because it’s a record in the [[Repository]], enforcement happens across the network, not just in one app.',
    ref: 'https://docs.bsky.app/docs/advanced-guides/moderation',
    refLabel: 'Moderation docs',
  },
  {
    term: 'Mute',
    cat: 'moderation',
    def: 'A private preference to stop seeing an account’s content, stored by the [[AppView]] rather than as a public [[Record]]. Unlike a [[Block]], the other account is unaware and unaffected.',
    ref: 'https://docs.bsky.app/docs/advanced-guides/moderation',
    refLabel: 'Moderation docs',
  },

  // --------------------------------------------------------------- bluesky
  {
    term: 'Bluesky',
    aka: ['bsky'],
    cat: 'bluesky',
    def: 'The first and largest application built on the AT Protocol — a microblogging social app. Also the company (Bluesky PBC) that develops both the app and much of the core protocol. atproto is bigger than Bluesky, but Bluesky is where most people meet it.',
    ref: 'https://bsky.social/about',
    refLabel: 'bsky.social',
  },
  {
    term: 'Post',
    cat: 'bluesky',
    def: 'A Bluesky status update — a [[Record]] of type `app.bsky.feed.post` in a user’s [[Repository]]. May contain text, [[Facet|facets]], embeds (images, [[Quote post|quotes]], links), and reply references.',
    ref: 'https://docs.bsky.app/docs/advanced-guides/posts',
    refLabel: 'Posts guide',
  },
  {
    term: 'Facet',
    cat: 'bluesky',
    def: 'A byte-range annotation on [[Post]] text marking a link, [[Mention]], or hashtag. Bluesky posts store plain text plus facets rather than inline markup, so the raw text stays clean.',
    ref: 'https://docs.bsky.app/docs/advanced-guides/post-richtext',
    refLabel: 'Rich text guide',
  },
  {
    term: 'Timeline',
    cat: 'bluesky',
    def: 'The default reverse-chronological feed of posts from accounts you [[Follow]], served by the [[AppView]] via `app.bsky.feed.getTimeline`. Distinct from a [[Feed generator|custom feed]].',
    ref: 'https://docs.bsky.app/docs/advanced-guides/feeds',
    refLabel: 'Feeds guide',
  },
  {
    term: 'Like',
    cat: 'bluesky',
    def: 'A [[Record]] (`app.bsky.feed.like`) referencing a [[Post]] by its [[AT-URI]] and [[CID]]. Because it’s a public record, like counts can be computed by any [[AppView]].',
    ref: 'https://github.com/bluesky-social/atproto/tree/main/lexicons/app/bsky/feed',
    refLabel: 'Feed lexicons',
  },
  {
    term: 'Repost',
    cat: 'bluesky',
    def: 'A [[Record]] (`app.bsky.feed.repost`) that re-shares another [[Post]] to your followers, the analogue of a retweet.',
    ref: 'https://github.com/bluesky-social/atproto/tree/main/lexicons/app/bsky/feed',
    refLabel: 'Feed lexicons',
  },
  {
    term: 'Follow',
    cat: 'bluesky',
    def: 'A [[Record]] (`app.bsky.graph.follow`) in your [[Repository]] pointing at another account’s [[DID]]. The social graph is just public records, so it’s portable and reusable across apps.',
    ref: 'https://github.com/bluesky-social/atproto/tree/main/lexicons/app/bsky/graph',
    refLabel: 'Graph lexicons',
  },
  {
    term: 'Quote post',
    cat: 'bluesky',
    def: 'A [[Post]] that embeds another post (`app.bsky.embed.record`) alongside your own commentary.',
    ref: 'https://docs.bsky.app/docs/advanced-guides/posts',
    refLabel: 'Posts guide',
  },
  {
    term: 'Thread',
    cat: 'bluesky',
    def: 'A chain of [[Post|posts]] connected by reply references (each reply names its parent and the thread root). The [[AppView]] assembles these into the threaded view you see.',
    ref: 'https://docs.bsky.app/docs/advanced-guides/posts',
    refLabel: 'Posts guide',
  },
  {
    term: 'List',
    cat: 'bluesky',
    def: 'A user-curated set of accounts (`app.bsky.graph.list`), usable as a feed, a mute list, or a moderation list. Like everything else, it’s a public [[Record]].',
    ref: 'https://github.com/bluesky-social/atproto/tree/main/lexicons/app/bsky/graph',
    refLabel: 'Graph lexicons',
  },
  {
    term: 'Starter pack',
    cat: 'bluesky',
    def: 'A shareable bundle (`app.bsky.graph.starterpack`) of accounts and [[Feed generator|feeds]] to follow, designed to help new users get set up quickly.',
    ref: 'https://docs.bsky.app/docs/advanced-guides/starter-packs',
    refLabel: 'Starter packs guide',
  },
  {
    term: 'Profile',
    cat: 'bluesky',
    def: 'The singleton [[Record]] (`app.bsky.actor.profile`, [[Record Key|rkey]] `self`) holding a user’s display name, description, and avatar/banner [[Blob|blobs]].',
    ref: 'https://github.com/bluesky-social/atproto/tree/main/lexicons/app/bsky/actor',
    refLabel: 'Actor lexicons',
  },
  {
    term: 'Direct message',
    abbr: 'DM',
    aka: ['chat'],
    cat: 'bluesky',
    def: 'Private one-to-one messages in Bluesky (`chat.bsky.*`). Currently routed through Bluesky’s own service rather than stored as public [[Repository]] records, and not yet end-to-end encrypted.',
    ref: 'https://docs.bsky.app/docs/api/chat-bsky-convo-send-message',
    refLabel: 'Chat API',
  },

  // ------------------------------------------------------------- ecosystem
  {
    term: 'Bluesky PBC',
    aka: ['Bluesky Social PBC'],
    cat: 'ecosystem',
    def: 'The public-benefit company that develops the AT Protocol and the [[Bluesky]] app. It runs reference infrastructure (a big [[PDS]], the [[PLC directory]], a [[Relay]]) but the protocol is designed so others can run their own.',
    ref: 'https://bsky.social/about',
    refLabel: 'bsky.social',
  },
  {
    term: 'Lexicon community',
    aka: ['third-party lexicons'],
    cat: 'ecosystem',
    def: 'The growing set of non-Bluesky apps defining their own [[Lexicon|lexicons]] under their own [[NSID]] namespaces (photos, blogging, events, and more), all sharing the same identity and repo layer.',
    ref: 'https://atproto.com/guides/applications',
    refLabel: 'Building applications',
  },
  {
    term: 'Statusphere',
    cat: 'ecosystem',
    def: 'The official example application in the atproto docs — a tiny app that teaches how to define a [[Lexicon]], write [[Record|records]], and read the [[Firehose]]. The canonical “hello world” for the protocol.',
    ref: 'https://atproto.com/guides/applications',
    refLabel: 'Building applications',
  },
  {
    term: 'Personal Data Server hosting',
    aka: ['self-hosting'],
    cat: 'ecosystem',
    def: 'Running your own [[PDS]] so you fully control your account and data. Bluesky publishes a self-hosting guide and container image; a self-hosted PDS federates with the rest of the [[Atmosphere]].',
    ref: 'https://atproto.com/guides/self-hosting',
    refLabel: 'Self-hosting guide',
  },
];
